// Path-based router (History API). GitHub Pages has no server-side
// rewrites, so a hard load or refresh on a route like /resume relies on
// dist/404.html (generated by scripts/generate-seo.mjs as a copy of
// dist/index.html) being served for any unmatched path — the app then
// boots normally and this router reads the real URL the browser already
// has.

import { trackPageView } from "./analytics";

type Handler = (params: URLSearchParams) => void | Promise<void>;

const routes = new Map<string, Handler>();
let fallback: Handler | null = null;

export function route(path: string, handler: Handler): void {
  routes.set(path, handler);
}

export function notFound(handler: Handler): void {
  fallback = handler;
}

function parse(): { path: string; params: URLSearchParams } {
  return { path: location.pathname || "/", params: new URLSearchParams(location.search) };
}

function dispatch(): void {
  const { path, params } = parse();
  const handler = routes.get(path) ?? fallback;
  // Reset scroll on every navigation so each "page" starts at the top.
  window.scrollTo(0, 0);
  trackPageView(path + location.search);
  handler?.(params);
}

export function start(): void {
  window.addEventListener("popstate", dispatch);

  // Intercept clicks on plain same-page-origin links (href="/...") so they
  // go through pushState instead of a full page reload. Anything else —
  // external links, target="_blank", download links, in-page "#" fragment
  // anchors, modified clicks (ctrl/cmd/shift/middle-click) — is left alone.
  document.addEventListener("click", (e) => {
    if (e.defaultPrevented || e.button !== 0) return;
    if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
    const a = (e.target as HTMLElement).closest("a");
    if (!a) return;
    const href = a.getAttribute("href");
    if (!href || !href.startsWith("/") || href.startsWith("//")) return;
    if (a.target && a.target !== "_self") return;
    if (a.hasAttribute("download")) return;
    e.preventDefault();
    navigate(href);
  });

  dispatch();
}

export function navigate(path: string): void {
  if (location.pathname + location.search !== path) {
    history.pushState(null, "", path);
  }
  // Re-dispatch even when the path hasn't changed (e.g. clicking a link to
  // the page already open).
  dispatch();
}
